In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from  sklearn.compose import ColumnTransformer 
import warnings
warnings.filterwarnings('ignore')

In [22]:
store_data = pd.read_csv('D:\\Data Science Roadmap and Practice\\Machine Learning Projects\\Market_Pulse_Analyzing_Popularity_Patterns_for_Apparel_Brands\\notebook\\Data\\store_data_updated.csv')
store_data

store_ratio  basket_ratio  category_1  store_score  category_2  \
0           0.756        0.6090           3       -7.927           1   
1           0.532        0.0872           4      -20.407           0   
2           0.373        0.1120           7      -22.063           1   
3           0.614        0.6140           8      -11.339           0   
4           0.453        0.2060           1      -10.764           0   
...           ...           ...         ...          ...         ...   
4444        0.380        0.2190           4      -13.273           0   
4445        0.405        0.3540           7      -14.391           1   
4446        0.362        0.9170           6       -3.003           0   
4447        0.846        0.5440           0       -7.403           1   
4448        0.709        0.6200          10       -4.138           1   

      store_presence   score_1  score_2  score_3  score_4    time  popularity  
0            0.21700  0.004740   0.0960   0.5370  117.023  155720           4  
1            0.95400  0.954000   0.0951   0.1870  131.494  185829           4  
2            0.99200  0.914000   0.1040   0.5010  110.651  144264           4  
3            0.50500  0.001740   0.0561   0.5570  159.971  348083           4  
4            0.92500  0.000064   0.0937   0.0565  104.960  227062           3  
...              ...       ...      ...      ...      ...     ...         ...  
4444         0.91700  0.010400   0.0827   0.0517   73.537  242265           4  
4445         0.82800  0.816000   0.1040   0.2560  142.061  324696           4  
4446         0.07250  0.000015   0.0938   0.4770  156.090  196547           4  
4447         0.00142  0.861000   0.1040   0.2250  140.005  261930           4  
4448         0.42500  0.000000   0.0822   0.6580  154.026  192571           4  

[4449 rows x 12 columns]

In [23]:
X = store_data.loc[:,['store_ratio','basket_ratio','category_1','store_score','category_2','store_presence','score_1','score_2','score_3','score_4','time']]
y = store_data.loc[:,['popularity']]

In [24]:
X

store_ratio  basket_ratio  category_1  store_score  category_2  \
0           0.756        0.6090           3       -7.927           1   
1           0.532        0.0872           4      -20.407           0   
2           0.373        0.1120           7      -22.063           1   
3           0.614        0.6140           8      -11.339           0   
4           0.453        0.2060           1      -10.764           0   
...           ...           ...         ...          ...         ...   
4444        0.380        0.2190           4      -13.273           0   
4445        0.405        0.3540           7      -14.391           1   
4446        0.362        0.9170           6       -3.003           0   
4447        0.846        0.5440           0       -7.403           1   
4448        0.709        0.6200          10       -4.138           1   

      store_presence   score_1  score_2  score_3  score_4    time  
0            0.21700  0.004740   0.0960   0.5370  117.023  155720  
1            0.95400  0.954000   0.0951   0.1870  131.494  185829  
2            0.99200  0.914000   0.1040   0.5010  110.651  144264  
3            0.50500  0.001740   0.0561   0.5570  159.971  348083  
4            0.92500  0.000064   0.0937   0.0565  104.960  227062  
...              ...       ...      ...      ...      ...     ...  
4444         0.91700  0.010400   0.0827   0.0517   73.537  242265  
4445         0.82800  0.816000   0.1040   0.2560  142.061  324696  
4446         0.07250  0.000015   0.0938   0.4770  156.090  196547  
4447         0.00142  0.861000   0.1040   0.2250  140.005  261930  
4448         0.42500  0.000000   0.0822   0.6580  154.026  192571  

[4449 rows x 11 columns]

In [25]:
y

popularity
0              4
1              4
2              4
3              4
4              3
...          ...
4444           4
4445           4
4446           4
4447           4
4448           4

[4449 rows x 1 columns]

In [26]:
numerical_feature = X.select_dtypes(exclude = 'object').columns
categorical_feature = X.select_dtypes(include = 'object').columns

numerical_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer([
    ('OneHotEncoder',oh_transformer,categorical_feature),
    ('StandardScaler', numerical_transformer, numerical_feature)
])


In [27]:
X  = preprocessor.fit_transform(X)

In [28]:
X

array([[ 0.95927761,  0.45356381, -0.61457781, ...,  0.33794357,
         0.10261763, -0.93240361],
       [-0.24134914, -1.33791096, -0.33336248, ..., -0.95189936,
         0.61339567, -0.43411932],
       [-1.09357973, -1.25276612,  0.51028352, ...,  0.20527401,
        -0.12229272, -1.12199293],
       ...,
       [-1.15253908,  1.51100771,  0.22906819, ...,  0.11682764,
         1.48155243, -0.25674341],
       [ 1.44167229,  0.23040195, -1.45822381, ..., -0.81185927,
         0.91380558,  0.82530255],
       [ 0.70736039,  0.49132966,  1.35392952, ...,  0.7838607 ,
         1.40870012, -0.32254362]])

In [29]:
X.shape

(4449, 11)

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [31]:
X_train

array([[-1.28117766, -1.58785224,  1.63514485, ..., -1.25409114,
        -1.63020153,  0.87903828],
       [ 0.87351856,  1.1230494 , -0.61457781, ...,  1.27400101,
         1.2670546 , -0.21952393],
       [-0.54686576,  1.77536869, -0.05214715, ..., -1.49400192,
         0.38534392,  0.68277957],
       ...,
       [-0.35926783,  0.70762501, -1.45822381, ..., -0.86345299,
         1.61666807,  0.05878644],
       [-1.53845482,  1.16081525, -0.33336248, ..., -0.05637984,
         1.99247166,  0.02459549],
       [-0.36998772,  1.20201437, -0.89579314, ..., -1.12510684,
         0.13742014,  0.49942936]])

In [32]:
y_train

popularity
1220           4
353            4
759            4
1222           1
2810           4
...          ...
4426           4
466            4
3092           4
3772           5
860            4

[3559 rows x 1 columns]

In [33]:
def evaluate_model(true,predict):
    accuracyscore = accuracy_score(true,predict)
    precisionscore = precision_score(true,predict, average='weighted')
    recallscore = recall_score(true,predict, average='weighted')
    f1score = f1_score(true,predict, average='weighted')
    confusionmatrix = confusion_matrix(true,predict)

    return accuracyscore, precisionscore, recallscore, f1score, confusionmatrix

In [36]:
models = {
    'KNeighborsClassifier' : KNeighborsClassifier(),
    'GaussianNB' : GaussianNB(),
    'SVC' : SVC(),
    'DecisionTreeClassifier' : DecisionTreeClassifier(),
    'RandomForestClassifier' : RandomForestClassifier(),
    'AdaBoostClassifier' : AdaBoostClassifier(),
    'GradientBoostingClassifier' : GradientBoostingClassifier()
    
}

model_list = []
accuracyscore_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    y_train_predict = model.predict(X_train)
    y_test_predict = model.predict(X_test)

    model_train_accuracyscore, model_train_precisionscore, model_train_recallscore, model_train_f1score, model_train_confusionmatrix = evaluate_model(y_train,y_train_predict)

    model_test_accuracyscore, model_test_precisionscore, model_test_recallscore, model_test_f1score, model_test_confusionmatrix = evaluate_model(y_test,y_test_predict)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model performance for test set')
    print('- Accuracy Score: {:.4f}'.format(model_test_accuracyscore))
    print('- Precision Recall Score: {:.4f}'.format(model_test_precisionscore))
    print('- Recall Score: {:.4f}'.format(model_test_recallscore))
    print('- F1 Score: {:.4f}'.format(model_test_f1score))
    print('- Confusion Matrix:\n ',(model_test_confusionmatrix))

    print('Model performance for train set')
    print('- Accuracy Score: {:.4f}'.format(model_train_accuracyscore))
    print('- Precision Recall Score: {:.4f}'.format(model_train_precisionscore))
    print('- Recall Score: {:.4f}'.format(model_train_recallscore))
    print('- F1 Score: {:.4f}'.format(model_train_f1score))
    print('- Confusion Matrix:\n ',(model_train_confusionmatrix))

    print('='*35)
    print('\n')


KNeighborsClassifier
Model performance for test set
- Accuracy Score: 0.8326
- Precision Recall Score: 0.7902
- Recall Score: 0.8326
- F1 Score: 0.8104
- Confusion Matrix:
  [[  0   3   8   0]
 [  2  12  70   0]
 [  2  43 729   1]
 [  0   5  15   0]]
Model performance for train set
- Accuracy Score: 0.8733
- Precision Recall Score: 0.8386
- Recall Score: 0.8733
- F1 Score: 0.8486
- Confusion Matrix:
  [[   7   10   41    1]
 [   1  122  249    1]
 [   2   76 2979    0]
 [   0   21   49    0]]


GaussianNB
Model performance for test set
- Accuracy Score: 0.7596
- Precision Recall Score: 0.8426
- Recall Score: 0.7596
- F1 Score: 0.7875
- Confusion Matrix:
  [[  0   7   4   0]
 [  0  53  31   0]
 [  0 152 623   0]
 [  0  17   3   0]]
Model performance for train set
- Accuracy Score: 0.7539
- Precision Recall Score: 0.8333
- Recall Score: 0.7539
- F1 Score: 0.7754
- Confusion Matrix:
  [[   1   36   22    0]
 [   0  216  157    0]
 [   0  591 2466    0]
 [   0   37   33    0]]


SVC
Model 